TRUNCATE TABLE NOTAS_CREDITO;

BULK INSERT NOTAS_CREDITO
FROM 'C:\Proyectos\Ecuador\CMI_SellOut_Ecuador\BaseDatos\BDPRUEBA.csv'
WITH (FIELDTERMINATOR=';', FIRSTROW=2, CODEPAGE='ACP');

TRUNCATE TABLE BASE_INICIAL_VENTAS;

BULK INSERT BASE_INICIAL_VENTAS
FROM 'C:\Proyectos\Ecuador\CMI_SellOut_Ecuador\BaseDatos\BDPRUEBAVENTAS.csv'
WITH (FIELDTERMINATOR=';',FIRSTROW=2,CODEPAGE='ACP');

--UPDATE A
-- SET A.Clase_id = B.Clase_id
-- FROM TRASLADO A 
--	INNER JOIN Negocio$ B ON A.Negocio_id = B.Negocio_id 