/****** Script for SelectTopNRows command from SSMS  ******/
set language spanish

TRUNCATE TABLE CODIFY;

ALTER TABLE CODIFY ALTER COLUMN Importe VARCHAR(100);
ALTER TABLE CODIFY ALTER COLUMN VentaTon VARCHAR(100);
ALTER TABLE CODIFY ALTER COLUMN Tunidades VARCHAR(100);

  BULK INSERT [CODIFY]
FROM 'C:\Proyectos\Ecuador\PANALES\CODIFY_1.csv'
WITH (FIELDTERMINATOR=';',FIRSTROW=2,CODEPAGE='ACP');


UPDATE CODIFY
SET Importe = REPLACE(Importe,',','')
WHERE CHARINDEX(',', Importe) > 0;

UPDATE CODIFY
SET VentaTon = REPLACE(VentaTon,',','')
WHERE CHARINDEX(',', VentaTon) > 0;

UPDATE CODIFY
SET Tunidades = REPLACE(Tunidades,',','')
WHERE CHARINDEX(',', Tunidades) > 0;

ALTER TABLE CODIFY ALTER COLUMN Importe FLOAT;
ALTER TABLE CODIFY ALTER COLUMN VentaTon FLOAT;
ALTER TABLE CODIFY ALTER COLUMN Tunidades DECIMAL (18,2);

SET LANGUAGE US_ENGLISH;

DELETE CODIFY WHERE CodAlicorp IS NULL;
DELETE CODIFY WHERE CodAlicorp = '';