/****** Script for SelectTopNRows command from SSMS  ******/
SET LANGUAGE SPANISH;

DELETE FROM CODIFY_HISTORICA WHERE LEFT(Fecha,7) = '2022-06';

BULK INSERT CODIFY_HISTORICA
FROM 'C:\Proyectos\Ecuador\PANALES\CODIFY_1.csv'
WITH (FIELDTERMINATOR=';',FIRSTROW=2,CODEPAGE='ACP');

TRUNCATE TABLE CODIFY;

ALTER TABLE CODIFY ALTER COLUMN Importe VARCHAR(100);
ALTER TABLE CODIFY ALTER COLUMN VentaTon VARCHAR(100);
ALTER TABLE CODIFY ALTER COLUMN Tunidades VARCHAR(100);

INSERT INTO CODIFY
SELECT *
FROM CODIFY_HISTORICA
WHERE DATEPART(YEAR,Fecha) = 2022 AND DATEPART(MONTH,Fecha) = 06;

INSERT INTO CODIFY
SELECT *
FROM CODIFY_HISTORICA
WHERE DATEPART(YEAR,Fecha) = 2022 AND DATEPART(MONTH,Fecha) = 05;

------------------USAR CUANDO LLEGUE EL 2023------------------------------------------------------
--INSERT INTO CODIFY
--SELECT *
--FROM CODIFY_HISTORICA
--WHERE DATEPART(YEAR,Fecha) = PONER AÑOPASADO AND DATEPART(MONTH,Fecha) = PONER MES DE AÑO PASADO;
-----------------------------------------------------------------------------------------------------------


UPDATE CODIFY
SET Importe = REPLACE(Importe,',','')
WHERE CHARINDEX(',', Importe) > 0;

UPDATE CODIFY
SET VentaTon = REPLACE(VentaTon,',','')
WHERE CHARINDEX(',', VentaTon) > 0;

UPDATE CODIFY
SET Tunidades = REPLACE(Tunidades,',','')
WHERE CHARINDEX(',', Tunidades) > 0;

ALTER TABLE CODIFY ALTER COLUMN Importe FLOAT;
ALTER TABLE CODIFY ALTER COLUMN VentaTon FLOAT;
ALTER TABLE CODIFY ALTER COLUMN Tunidades DECIMAL (18,2);

SET LANGUAGE US_ENGLISH;

DELETE CODIFY WHERE CodAlicorp IS NULL;
DELETE CODIFY WHERE CodAlicorp = '';
DELETE FROM CODIFY WHERE Importe = 0;
DELETE FROM CODIFY WHERE Importe IS NULL;

UPDATE A SET CodAlicorp = TRIM(CodAlicorp) FROM CODIFY A;
UPDATE A SET [CODIGODISTRIBUIDOR] = TRIM([CODIGODISTRIBUIDOR]) FROM CODIFY A;
UPDATE A SET [DISTRIBUIDOR] = TRIM([DISTRIBUIDOR]) FROM CODIFY A;

UPDATE CODIFY
SET CodAlicorp = CASE CodAlicorp
	WHEN '8309000' THEN '8309119'
	WHEN '8309001' THEN '8309120'
	WHEN '8309002' THEN '8309121'
	WHEN '8309003' THEN '8309122'
	WHEN '8309007' THEN '8309126'
	WHEN '8309009' THEN '8309128' 
	WHEN 'P.3300147' THEN '3300147'
	WHEN '293369' THEN '29369' ELSE CodAlicorp END;