/****** Script for SelectTopNRows command from SSMS  ******/

IF OBJECT_ID(N'tempdb..#SUPERPRUEBAIF') IS NOT NULL DROP TABLE  #SUPERPRUEBAIF;

  DECLARE @HOLI INT
  SET @HOLI = YEAR(GETDATE())
  PRINT @HOLI
   
  IF @HOLI IN (SELECT YEAR(FNC) FROM [LF_NC_HISTORICO] ) 

   SELECT *
   INTO #SUPERPRUEBAIF
   FROM
  
  (SELECT distinct FNC FROM [LF_NC_HISTORICO] WHERE FNC = '2022-03-14') A  ELSE SELECT DISTINCT FNC 
  FROM [LF_NC_HISTORICO] WHERE FNC = '2020-07-29' 


