DELETE FROM KPIS WHERE 1=1 
AND Agencia_Distribuidora IN ('ATI CAMPAÑA FLAVIA MARINA', 'CONTRERAS DELGADO WASHINGTON ','OLGER ARMIJOS DISTRIBUCIONES S.A.S',
'D LOGIS CODILOGIS CIA. LTDA.', 'BARNUEVO VALAREZO & GCP CIA LTDA', 'PRODISPRO CIA.LTDA','REPREMARVA CIA. LTDA.','REPRESENTACIONES J.LEONARDO SORIA',
'FREDVY S.A.') 

AND Periodo IS NULL