/****** Script for SelectTopNRows command from SSMS  ******/

--SELECT categoria, AÑO, Sales
----INTO UNPIVOT2
--FROM
----------------------------------------------------------
--(SELECT  *
--  FROM [CmiSellOutEcuador].[dbo].[unpivot]) HOLI
--	UNPIVOT
--	(Sales FOR AÑO IN (AMBATO_TN, CUENCA_TN, SANTA_ELENA, SANTO_DGO_TN)
--	) AS PRUEBA_UNPIVOT
-----------------------------------
-- LO QUE ESTA ENTRE RAYAS SERIA COMO UN ESPECIE DE TABLA TEMPORAL LLAMADA PRUEBA_UNPIVOT
--CREADA DE LA TABLA HOLI QUE VIENE DEL  tabla unpivot

USE CmiSellOutEcuador;

SET LANGUAGE US_ENGLISH;

DECLARE @dia DATE;
DECLARE @workday INT;
--Dia hábil de la fecha
DECLARE @workday_MA INT;
--Dia hábil que hay en el mes anterior
DECLARE @d1 AS VARCHAR(20);

SELECT @dia= DATEADD(DAY,-1,SYSDATETIME());
-- poner el último día de ventas

SELECT @d1= TRY_CONVERT(VARCHAR(20), TRY_CONVERT(DATE, @dia,103),103);

PRINT @dia;
PRINT 'd1 '+ @d1;


TRUNCATE TABLE NuevoPlanHularussFormato;

BULK INSERT NuevoPlanHularussFormato
FROM 'C:\Proyectos\Ecuador\HULARUSS\NuevoPlanHularussFormato.csv'
WITH (FIELDTERMINATOR=';',FIRSTROW=2,CODEPAGE='ACP');

DELETE FROM NuevoPlanHularussFormato WHERE CodAlicorp LIKE '%TOTAL%'

UPDATE A SET CodAlicorp = TRIM(CodAlicorp) FROM NuevoPlanHularussFormato A;
UPDATE A SET Canal = TRIM(Canal) FROM NuevoPlanHularussFormato A;
UPDATE NuevoPlanHularussFormato SET CodAlicorp = LEFT(CodAlicorp,CHARINDEX(' ',CodAlicorp)-1);

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO;

SELECT Canal, CodAlicorp, NomOficina, MontoCantidad
INTO #HULARUSS_PLAN_NUEVO
FROM
(SELECT * FROM NuevoPlanHularussFormato) PLAN_HULARUSS
UNPIVOT
(MontoCantidad FOR NomOficina IN (AMBATO,AMBATO_TN,CHONE,CHONE_TN,CUENCA,CUENCA_TN,ESMERALDAS,ESMERALDAS_TN,GUAYAQUIL,GUAYAQUIL_TN,IBARRA,IBARRA_TN,LOJA,LOJA_TN,MACHALA,MACHALA_TN,
MANABI,MANABI_TN,MILAGRO,MILAGRO_TN,ORIENTE,ORIENTE_TN,QUEVEDO,QUEVEDO_TN,QUITO,QUITO_TN,SANTA_ELENA,SANTA_ELENA_TN,SANTO_DGO,SANTO_DGO_TN)) AS PLAN_UNPIVOT

UPDATE A SET Canal = 'MINORISTAS' FROM #HULARUSS_PLAN_NUEVO A  WHERE Canal = 'TIENDA';

DELETE FROM #HULARUSS_PLAN_NUEVO WHERE NomOficina IN ('CHONE', 'CHONE_TN', 'ORIENTE', 'ORIENTE_TN' )

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_TON') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_TON;

SELECT *
INTO #HULARUSS_PLAN_NUEVO_TON
FROM #HULARUSS_PLAN_NUEVO
WHERE NomOficina IN('AMBATO_TN','CHONE_TN','CUENCA_TN','ESMERALDAS_TN','GUAYAQUIL_TN',
'IBARRA_TN','LOJA_TN','MACHALA_TN','MANABI_TN','MILAGRO_TN','ORIENTE_TN','QUEVEDO_TN',
'QUITO_TN','SANTA_ELENA_TN','SANTO_DGO_TN')

UPDATE A SET NomOficina = LEFT(NomOficina,LEN(NomOficina)-3) FROM #HULARUSS_PLAN_NUEVO_TON A;
--SELECT * FROM #HULARUSS_PLAN_NUEVO_TON WHERE MontoCantidad IS NULL

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_DOL') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_DOL;

SELECT *
INTO #HULARUSS_PLAN_NUEVO_DOL
FROM #HULARUSS_PLAN_NUEVO
WHERE NomOficina IN('AMBATO','CHONE','CUENCA','ESMERALDAS','GUAYAQUIL',
'IBARRA','LOJA','MACHALA','MANABI','MILAGRO','ORIENTE','QUEVEDO',
'QUITO','SANTA_ELENA','SANTO_DGO')

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_MAYOR') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_MAYOR;

SELECT @d1 Fecha, A.Canal Canal, A.CodAlicorp CodAlicorp, A.NomOficina, A.MontoCantidad Plan_Ton, B.MontoCantidad Plan_Dol
INTO #HULARUSS_PLAN_NUEVO_MAYOR
FROM #HULARUSS_PLAN_NUEVO_TON A 
	LEFT JOIN #HULARUSS_PLAN_NUEVO_DOL B ON A.CodAlicorp = B.CodAlicorp AND A.NomOficina = B.NomOficina AND A.Canal = B.Canal
WHERE A.Canal = 'MAYORISTAS'

DELETE #HULARUSS_PLAN_NUEVO_MAYOR WHERE Plan_Dol = 0 AND Plan_Ton = 0;

UPDATE #HULARUSS_PLAN_NUEVO_MAYOR 
SET Fecha = RIGHT(Fecha,9)
WHERE Fecha LIKE '0_/%'

UPDATE #HULARUSS_PLAN_NUEVO_MAYOR
SET CodAlicorp = CASE CodAlicorp
	WHEN '8309000' THEN '8309119'
	WHEN '8309001' THEN '8309120'
	WHEN '8309002' THEN '8309121'
	WHEN '8309003' THEN '8309122'
	WHEN '8309007' THEN '8309126'
	WHEN '8309009' THEN '8309128'
	WHEN '293369' THEN '29369' ELSE CodAlicorp END;


	
INSERT INTO #HULARUSS_DUMMY
SELECT B.Fecha, A.Agencia, C.CodAlicorp
FROM  (SELECT F.Agencia FROM (SELECT DISTINCT NomOficina FROM #HULARUSS_PLAN_NUEVO_MAYOR) D LEFT JOIN MAESTRO_AGENCIAS F ON D.NomOficina = F.NomOficina)  A CROSS JOIN #FECHA B
CROSS JOIN (SELECT DISTINCT CodAlicorp FROM #HULARUSS_PLAN_NUEVO_MAYOR) C


IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_MINOR') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_MINOR;

SELECT @d1 Fecha, A.Canal Canal, A.CodAlicorp CodAlicorp, A.NomOficina, A.MontoCantidad Plan_Ton, B.MontoCantidad Plan_Dol
INTO #HULARUSS_PLAN_NUEVO_MINOR
FROM #HULARUSS_PLAN_NUEVO_TON A 
	LEFT JOIN #HULARUSS_PLAN_NUEVO_DOL B ON A.CodAlicorp = B.CodAlicorp AND A.NomOficina = B.NomOficina AND A.Canal = B.Canal
WHERE A.Canal = 'MINORISTAS'

DELETE #HULARUSS_PLAN_NUEVO_MINOR WHERE Plan_Dol = 0 AND Plan_Ton = 0;

UPDATE #HULARUSS_PLAN_NUEVO_MINOR 
SET Fecha = RIGHT(Fecha,9)
WHERE Fecha LIKE '0_/%'

UPDATE #HULARUSS_PLAN_NUEVO_MINOR
SET CodAlicorp = CASE CodAlicorp
	WHEN '8309000' THEN '8309119'
	WHEN '8309001' THEN '8309120'
	WHEN '8309002' THEN '8309121'
	WHEN '8309003' THEN '8309122'
	WHEN '8309007' THEN '8309126'
	WHEN '8309009' THEN '8309128'
	WHEN '293369' THEN '29369' ELSE CodAlicorp END;

INSERT INTO #HULARUSS_DUMMY
SELECT B.Fecha, A.Agencia, C.CodAlicorp
FROM  (SELECT F.Agencia FROM (SELECT DISTINCT NomOficina FROM #HULARUSS_PLAN_NUEVO_MINOR) D LEFT JOIN MAESTRO_AGENCIAS F ON D.NomOficina = F.NomOficina)  A CROSS JOIN #FECHA B
CROSS JOIN (SELECT DISTINCT CodAlicorp FROM #HULARUSS_PLAN_NUEVO_MINOR) C
--recordar que debo descomentar linea 827 WHERE A.Canal = 'MAYORISTAS';
--falta poner dummies
--parece que las dos agencias que hay que hacer updates son las mismas que los updates del formato del plan anterior

--para el master
--UPDATE A SET Canal = TRIM(Canal) FROM VENTAS_HULARUSS A linea 768
--UPDATE A SET A.Canal = 'MAYORISTAS' FROM VENTAS_HULARUSS A 
--	WHERE  A.Canal <> 'TAT' linea 814

--select * from #HULARUSS_PLAN_NUEVO_MINOR
--('AMBATO','AMBATO_TN','CHONE','CHONE_TN','CUENCA','CUENCA_TN','ESMERALDAS','ESMERALDAS_TN','GUAYAQUIL','GUAYAQUIL_TN',
--'IBARRA', 'IBARRA_TN','LOJA','LOJA_TN','MACHALA','MACHALA_TN','MANABI','MANABI_TN','MILAGRO','MILAGRO_TN','ORIENTE','ORIENTE_TN','QUEVEDO','QUEVEDO_TN',
--'QUITO','QUITO_TN','SANTA_ELENA','SANTA_ELENA_TN','SANTO_DGO','SANTO_DGO_TN')
