/****** Script for SelectTopNRows command from SSMS  ******/

SELECT categoria, AÑO, Sales
--INTO UNPIVOT2
FROM
--------------------------------------------------------
(SELECT  *
  FROM [CmiSellOutEcuador].[dbo].[unpivot]) HOLI
	UNPIVOT
	(Sales FOR AÑO IN (AMBATO_TN, CUENCA_TN, SANTA_ELENA, SANTO_DGO_TN)
	) AS PRUEBA_UNPIVOT
---------------------------------
-- LO QUE ESTA ENTRE RAYAS SERIA COMO UN ESPECIE DE TABLA TEMPORAL LLAMADA PRUEBA_UNPIVOT
--CREADA DE LA TABLA HOLI QUE VIENE DEL  tabla unpivot


TRUNCATE TABLE NuevoPlanHularussFormato;

BULK INSERT NuevoPlanHularussFormato
FROM 'C:\Proyectos\Ecuador\HULARUSS\NuevoPlanHularussFormato.csv'
WITH (FIELDTERMINATOR=';',FIRSTROW=2,CODEPAGE='ACP');

DELETE FROM NuevoPlanHularussFormato WHERE CodAlicorp LIKE '%TOTAL%'

UPDATE A SET CodAlicorp = TRIM(CodAlicorp) FROM NuevoPlanHularussFormato A;
UPDATE A SET Canal = TRIM(Canal) FROM NuevoPlanHularussFormato A;
UPDATE NuevoPlanHularussFormato SET CodAlicorp = LEFT(CodAlicorp,CHARINDEX(' ',CodAlicorp)-1);

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO;

SELECT Canal, CodAlicorp, Agencia, MontoCantidad
INTO #HULARUSS_PLAN_NUEVO
FROM
(SELECT * FROM NuevoPlanHularussFormato) PLAN_HULARUSS
UNPIVOT
(MontoCantidad FOR Agencia IN (AMBATO,AMBATO_TN,CHONE,CHONE_TN,CUENCA,CUENCA_TN,ESMERALDAS,ESMERALDAS_TN,GUAYAQUIL,GUAYAQUIL_TN,IBARRA,IBARRA_TN,LOJA,LOJA_TN,MACHALA,MACHALA_TN,
MANABI,MANABI_TN,MILAGRO,MILAGRO_TN,ORIENTE,ORIENTE_TN,QUEVEDO,QUEVEDO_TN,QUITO,QUITO_TN,SANTA_ELENA,SANTA_ELENA_TN,SANTO_DGO,SANTO_DGO_TN)) AS PLAN_UNPIVOT

UPDATE A SET Canal = 'MINORISTAS' FROM #HULARUSS_PLAN_NUEVO A  WHERE Canal = 'TIENDA';

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_TON') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_TON;

SELECT *
INTO #HULARUSS_PLAN_NUEVO_TON
FROM #HULARUSS_PLAN_NUEVO
WHERE Agencia IN('AMBATO_TN','CHONE_TN','CUENCA_TN','ESMERALDAS_TN','GUAYAQUIL_TN',
'IBARRA_TN','LOJA_TN','MACHALA_TN','MANABI_TN','MILAGRO_TN','ORIENTE_TN','QUEVEDO_TN',
'QUITO_TN','SANTA_ELENA_TN','SANTO_DGO_TN')

UPDATE A SET Agencia = LEFT(Agencia,LEN(Agencia)-3) FROM #HULARUSS_PLAN_NUEVO_TON A;
--SELECT * FROM #HULARUSS_PLAN_NUEVO_TON WHERE MontoCantidad IS NULL

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_DOL') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_DOL;

SELECT *
INTO #HULARUSS_PLAN_NUEVO_DOL
FROM #HULARUSS_PLAN_NUEVO
WHERE Agencia IN('AMBATO','CHONE','CUENCA','ESMERALDAS','GUAYAQUIL',
'IBARRA','LOJA','MACHALA','MANABI','MILAGRO','ORIENTE','QUEVEDO',
'QUITO','SANTA_ELENA','SANTO_DGO')

IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_MAYOR') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_MAYOR;

SELECT A.Canal Canal, A.CodAlicorp CodAlicorp, A.Agencia, A.MontoCantidad Plan_Ton, B.MontoCantidad Plan_Dol
INTO #HULARUSS_PLAN_NUEVO_MAYOR
FROM #HULARUSS_PLAN_NUEVO_TON A 
	LEFT JOIN #HULARUSS_PLAN_NUEVO_DOL B ON A.CodAlicorp = B.CodAlicorp AND A.Agencia = B.Agencia AND A.Canal = B.Canal
WHERE A.Canal = 'MAYORISTAS'


IF OBJECT_ID(N'tempdb..#HULARUSS_PLAN_NUEVO_MINOR') IS NOT NULL DROP TABLE #HULARUSS_PLAN_NUEVO_MINOR;

SELECT A.Canal Canal, A.CodAlicorp CodAlicorp, A.Agencia, A.MontoCantidad Plan_Ton, B.MontoCantidad Plan_Dol
INTO #HULARUSS_PLAN_NUEVO_MINOR
FROM #HULARUSS_PLAN_NUEVO_TON A 
	LEFT JOIN #HULARUSS_PLAN_NUEVO_DOL B ON A.CodAlicorp = B.CodAlicorp AND A.Agencia = B.Agencia AND A.Canal = B.Canal
WHERE A.Canal = 'MINORISTAS'

--('AMBATO','AMBATO_TN','CHONE','CHONE_TN','CUENCA','CUENCA_TN','ESMERALDAS','ESMERALDAS_TN','GUAYAQUIL','GUAYAQUIL_TN',
--'IBARRA', 'IBARRA_TN','LOJA','LOJA_TN','MACHALA','MACHALA_TN','MANABI','MANABI_TN','MILAGRO','MILAGRO_TN','ORIENTE','ORIENTE_TN','QUEVEDO','QUEVEDO_TN',
--'QUITO','QUITO_TN','SANTA_ELENA','SANTA_ELENA_TN','SANTO_DGO','SANTO_DGO_TN')
