USE [CmiSellOutEcuador];
CREATE TABLE BASE_INICIAL_VENTAS(
	Regional VARCHAR(100) NULL,
	Agencia VARCHAR(100) NULL,
	Ciudad VARCHAR(100) NULL,
	IdVendedor VARCHAR(100) NULL,
	NVendedor VARCHAR(100) NULL,
	IdSupervisor VARCHAR(100)NULL,
	NSupervisor VARCHAR(100) NULL,
	TVendedor VARCHAR(100) NULL,
	RCliente VARCHAR(100) NULL,
	IdTarifa VARCHAR(100) NULL,
	Tcanal VARCHAR(100) NULL,
	Cliente VARCHAR(100) NULL,
	NomCliente VARCHAR(100) NULL,
	NOrden VARCHAR(100) NULL,
	Pos VARCHAR(100) NULL,
	Sec VARCHAR(100) NULL,
	FOrden VARCHAR(100) NULL,
	FEntrega VARCHAR(100) NULL,
	FFactura DATE NULL,
	CodArticulo VARCHAR(100) NOT NULL,
	Cntr VARCHAR(100) NULL,
	UVenta VARCHAR(100) NULL,
	DesArticulo VARCHAR(100) NULL,
	CodAlicorp VARCHAR(100) NULL,
	CantPerdida VARCHAR(100) NULL,
	CantEntregada VARCHAR(100) NULL,
	Kilos FLOAT NULL,
	Importe FLOAT NULL,
	Unidades VARCHAR(100) NULL,
	Cajas VARCHAR(100) NULL,
	FacUnitario VARCHAR(100) NULL,
	FactKilos VARCHAR(100) NULL,
	TUnidades VARCHAR(100) NULL,
	TipoLinea VARCHAR(100) NULL,
	TipoVenta VARCHAR(100) NULL,
	Division VARCHAR(100) NULL,
	Categoria VARCHAR(100) NULL,
	Marca VARCHAR(100) NULL,
	TipoProducto VARCHAR(100) NULL,
	SubCategoria VARCHAR(100) NULL,
	Variedad VARCHAR(100) NULL,
	SubMarca VARCHAR(100) NULL,
	DirComercial VARCHAR(100) NULL,
	GrupoProducto VARCHAR(100) NULL
	);

IF OBJECT_ID(N'tempdb..#Prueba1') IS NOT NULL DROP TABLE #Prueba1;

SELECT Regional
INTO #Prueba1
FROM NOTAS_CREDITO;


	--COMENZAMOS CON DROP
	LUEGO EN LA TABLA TEMPORRAL ALTERAMOS
