/****** Script for SelectTopNRows command from SSMS  ******/
SELECT
      [FNC]
    
  FROM [Alicorp].[dbo].[NOTAS_CREDITO]

  SELECT TRY_CONVERT(VARCHAR(20), FNC , 103) CONVERTIDO FROM [Alicorp].[dbo].[NOTAS_CREDITO]
  IF OBJECT_ID('[dbo].[CONVERTIDO]') IS NOT NULL DROP TABLE [dbo].[CONVERTIDO]

  SELECT TRY_CONVERT(VARCHAR(20), FNC , 103) CONVERTIDO
  INTO [dbo].[CONVERTIDO]
  FROM [Alicorp].[dbo].[NOTAS_CREDITO]
  SELECT * FROM CONVERTIDO
  --SI FUNCIONA

  UPDATE [Alicorp].[dbo].[NOTAS_CREDITO] SET FNC = TRY_CONVERT(VARCHAR(20), FNC , 103)